<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <NoWarn>$(NoWarn);IDE0090</NoWarn>
    <NoWarn>$(NoWarn);IDE0017</NoWarn>
    <NoWarn>$(NoWarn);IDE0028</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Update="lang.json" CopyToOutputDirectory="PreserveNewest" />
    <PackageReference Include="GtkSharp" Version="3.24.24.*" />
  </ItemGroup>

</Project>
